### ISSUE TITLE
Remove redefinition of PadListNames in the c template after 5.22.1

### ISSUE THREAD

**Issue by atoomic** [CpanelInc/perl-compiler#19]
view issue #16 for more details

**Comment by atoomic** [comment]
fixed with 5.22.1 and 5.23.0, we cannot remove it for now

**Comment by toddr** [comment]
@atoomic We need to confirm it's in the backport list for 5.22.1. they're proposing that list now.
https://github.com/toddr/perl/blob/maint-votes/votes-5.22.xml

**Comment by toddr** [comment]
This issue was moved to CpanelInc/temp1#11
