### ISSUE TITLE
Ask p5p about struct padlist xpadlarr_dbg

### ISSUE THREAD

**Issue by toddr** [CpanelInc/perl-compiler#2]
could it be a #if debug? nothing seems to use it.

**Comment by rurban** [comment]
> On Sep 24, 2015, at 10:12 AM, Todd Rinaldo <notifications@github.com> wrote:
> 
> could it be a #if debug? nothing seems to use it.

It needs to be in #ifdef DEBUGGING, yes.
It’s useful during debugging only.

Like bulk88’s patch to cperl.

**Comment by toddr** [comment]
This issue was moved to CpanelInc/temp1#2
