### ISSUE TITLE
Convert t/CORE into t/C-COMPILED/*.patch

### ISSUE THREAD

**Issue by toddr** [CpanelInc/perl-compiler#4]
Make t/CORE identical to what comes with that perl version. so it's easier to re-base patches and track blead.

**Comment by atoomic** [comment]
not needed anymore with the new structure, we have patches saved in a directory if needed and do not need to apply them each time we run a test. This is only useful when updating our core test suite, which for now does not happen a lot, as we mainly focus and one target version at a time

**Comment by toddr** [comment]
This issue was moved to CpanelInc/temp1#4
