### ISSUE TITLE
Import perl 5.22 CORE tests into cm522 and update/rebase t/C-COMPILED/*.patch

### ISSUE THREAD

**Issue by toddr** [CpanelInc/perl-compiler#5]

**Comment by atoomic** [comment]
this is done by a set of commits...
077470a..10621f

we should try to simplify the set of patches as most of them would be not required if using a t/ directory and not a t/CORE
we could reorganize the code as t/5.20.0/t/ and t/5.22.0/t/ and use a symlink for t/CORE if needed
this would make merges from 520 easier
it s a good thing if we can have mutliple test suite version in our repo,
we could submit upstream(B::C) something similar as the existing test suite in B::C is obsolete
